### PR TITLE
Refactor to community code pool, composer support

### PR DESCRIPTION
**Pull request by economixoffice**
Magento developers love composer, that's why I added a composer.json to make it ready for use via composer :) No need to install via Magento Connect/Marketplace any more.

The community code pool is the right codepool in this case (changed from local).

Have fun with it! :)

### CODE REVIEW

**Comment by michaelraberger** [comment]
thx E-CONOMIX ;)

**Comment by avoelkl** [comment]
Any news when this will be merged?

**Comment by avoelkl** [comment]
Hi, any updates on this?

**Comment by karim79** [comment]
Sorry for the delay.

**Pull request merged**
